### ISSUE TITLE
Can't add custom card

### ISSUE THREAD

**Issue by hotothehaha** [iantrich/config-template-card#76]
**Checklist:**

- [Y] I updated to the latest version available
- [Y] I cleared the cache of my browser

**Release with the issue:**
HA: 2021.8.7
Config template card 1.3.1

**Last working release (if known):**
N/A

**Browser and Operating System:**
Windows/chrome

Installed using HACS but getting the below error when trying to create the card. Noticed that the custom card wasn't available to add. Reinstalled using local files and had the same issue. For whatever reason, the cards not showing as an option to be added? Not sure what else to do to get this working, though I'm pretty new to this so I might just be dumb.

"No card or row or element defined

type: custom:config-template-card"

**Comment by iantrich** [comment]
This card does not have a UI editor and is not available in the card picker. You select "manual card" and then provide the required yaml. The error you are getting is because you have not provided all the required fields for the card's configuration. The readme could be a little more clear, but you need to provide a `card`, `row`, or `element` object in your config for it to be valid.

**Comment by hotothehaha** [comment]
Thanks. I thought it might be that but I had some trouble getting some of the code that others said worked to run properly. Even for the examples provided like the one for picture elements I'm getting a style error. 

Might just be me though, need to dig into it some more I guess

**Comment by iantrich** [comment]
Fixed style error in 1.3.4
